### ISSUE TITLE
will not connect to ssl enablet rabbitmq_management

### ISSUE THREAD

**Issue by Bjarke42** [NYTimes/collectd-rabbitmq#17]
i have tried to use it on my ssl enablet rabbitmq manager, but it does not provide any data. My assumption is that it cannot connect to rabbitmq manager using https.

**Comment by jimbydamonk** [comment]
I haven't had a change to play with this. 
Do you have any logs or other data to help debugging ?

**Comment by davewongillies** [comment]
Its because of [this line](https://github.com/NYTimes/collectd-rabbitmq/blob/master/rabbitmq.py#L10):
```
RABBIT_API_URL = "http://{host}:{port}/api/"
```

The code needs changing/fixing to allow for https connections. At my $WORK we've just hacked it to be:
```
RABBIT_API_URL = "{host}:{port}/api/"
```
And we pass in `https://some.host:15671` in the config but it'd be nicer to perhaps have an `SSL` `true|false` option or something.

**Comment by jimbydamonk** [comment]
So I have fixed this in the un merge develop branch. I am still testing the stuff in develop and getting everything set up (pypi, readthedocs etc) I will merge the PR in since it seems equivalent to what I put together.

**Comment by jimbydamonk** [comment]
#30 added support for turning on https
